### Register User API
POST http://localhost:8000/api/users
Content-Type: application/json
Accept: application/json

{
    "username": "chaerulumam",
    "password": "rahasia",
    "name": "Chaerul Umam"
}

### Login User API
POST http://localhost:8000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "chaerulumam",
    "password": "rahasia",
}

### Get Current User API
GET http://localhost:8000/api/users/current
Accept: application/json
Authorization: 5db542a7-d8cb-41a3-b2eb-eb7589654eef

### Update Current User API
PATCH http://localhost:8000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 5db542a7-d8cb-41a3-b2eb-eb7589654eef

{
    "name" : "Chaerul"
}

### Logout User API
DELETE http://localhost:8000/api/users/logout
Accept: application/json
Authorization: 5db542a7-d8cb-41a3-b2eb-eb7589654eef

{
  "data": true
}

### Create Contact API
POST http://127.0.0.1:8000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: 009a06d8-8ce7-4f4a-a5e2-c2d9f4b82e91
